export const PROFILE_REQUEST = 'PROFILE_REQUEST'
export const PROFILE_SUCCESS = 'PROFILE_SUCCESS'
export const PROFILE_FALIURE = 'PROFILE_FALIURE'
export const PEOPLE_ERROR = 'PEOPLE_ERROR'
export const PEOPLE_SUCCESS = 'PEOPLE_SUCCESS'


//not sure
export const GET_CHAT = "GET_CHAT"